set(tutorials_SETUP_PY_SETUP_MODULE "distutils.core")
set(tutorials_SETUP_PY_VERSION "0.0.0")
set(tutorials_SETUP_PY_SCRIPTS "")
set(tutorials_SETUP_PY_PACKAGES "")
set(tutorials_SETUP_PY_PACKAGE_DIRS "")
set(tutorials_SETUP_PY_MODULES "")
set(tutorials_SETUP_PY_MODULE_DIRS "")